"""Per-tool command specifications."""

from . import (
    archive_triage,
    artifact_triage,
    binary_disassembly,
    binary_run,
    binary_triage,
    computation_analysis,
    credential_login_probe,
    credential_harvest,
    ctf_exploit_probe,
    flag_harvest,
    host_inventory,
    http_content,
    http_form_probe,
    http_metadata,
    http_path_probe,
    pcap_review,
    repo_review,
    runtime_probe,
    script_execution,
    source_review,
    sqlite_review,
    tcp_banner_probe,
    vuln_scan,
)

ALL_COMMAND_TOOLS = (
    http_metadata,
    http_content,
    http_form_probe,
    artifact_triage,
    archive_triage,
    binary_triage,
    binary_disassembly,
    binary_run,
    computation_analysis,
    credential_login_probe,
    credential_harvest,
    ctf_exploit_probe,
    flag_harvest,
    sqlite_review,
    pcap_review,
    repo_review,
    runtime_probe,
    script_execution,
    source_review,
    host_inventory,
    tcp_banner_probe,
    http_path_probe,
    vuln_scan,
)

__all__ = ["ALL_COMMAND_TOOLS"]
