"""Prompt builder for LLM-selected worker tool capability."""

from __future__ import annotations

import json
from typing import Any

from killchain_docker.state.run_state import RunState
from killchain_docker.state.todos import TodoItem
from killchain_docker.tools.capabilities import ToolCapability, ToolGateway
from killchain_docker.workers.tool_contract_catalog import tool_metadata_contract
from killchain_docker.workers.tool_prompt_model import ToolUsePrompt
from killchain_docker.workers.tool_prompt_payload import tool_choice_payload
from killchain_docker.workers.tool_prompt_rules import script_reminder, shell_reminder


def build_tool_choice_prompt(
    *,
    worker_name: str,
    task: TodoItem,
    state: RunState,
    tool_gateway: ToolGateway,
    allowed_capabilities: list[ToolCapability | str] | None,
    prior_steps: list[dict[str, Any]] | None,
) -> ToolUsePrompt:
    allowed = {
        ToolCapability(capability)
        for capability in allowed_capabilities or list(tool_gateway.specs.keys())
    }
    allowed_values = sorted(capability.value for capability in allowed)
    catalog = [
        {
            "capability": capability.value,
            "tool_name": spec.tool_name,
            "default_timeout_s": spec.default_timeout_s,
            "metadata_contract": tool_metadata_contract(capability),
        }
        for capability, spec in tool_gateway.specs.items()
        if capability in allowed
    ]
    user_payload = tool_choice_payload(
        worker_name=worker_name,
        task=task,
        state=state,
        allowed=allowed,
        prior_steps=prior_steps,
        tool_catalog=catalog,
    )
    allowed_str = ", ".join(f"'{value}'" for value in allowed_values)
    system_prompt = f"You are {worker_name}. Your ONLY available capabilities are: [{allowed_str}]. You MUST choose exactly one capability from this list. Any other capability will be REJECTED - do not select capabilities you saw in evidence from other workers. Provide the metadata arguments needed by that capability using only the field names listed in its metadata_contract. {shell_reminder(allowed)}{script_reminder(allowed)}Use recent_evidence_context as grounded facts from previous tools. If prior_steps is non-empty, use those results to inform your choice - do not repeat a tool that already produced its evidence. If correction_context is present, you MUST fix the identified error in your next script - do not repeat the same broken approach. When the current todo or correction_context states a corrected value from a previous failure, it overrides older reference/source code and older evidence unless your next bounded diagnostic disproves it. If correction_context.execution_constraints contains do_not_iterate_values, your script_code MUST NOT put those exact values into range(), loop bounds, sleeps, brute-force searches, or linear counters. Use listed bounded_counter_candidates first, or explicitly skip the oversized interpretation and continue bounded enumeration. Do not depend on files generated by earlier shell.exec/script.exec calls, including files written under files_root; tool workspaces are snapshots. Read original challenge files directly or regenerate needed artifacts in the same tool call. Stay inside authorized_scope and files_root. Do not pivot to localhost, 127.0.0.1, or unrelated local services unless they are explicitly in authorized_scope. Do not search ambient directories such as /home outside files_root, /root, /etc, /tmp, /var, /opt, or shell startup files for flags or secrets unless a todo explicitly identifies those paths as challenge artifacts. Use run_memory as established facts from prior analysis. Use memory_updates only for facts already grounded in current state or prior evidence; do not use memory_updates to predict what the tool you are about to run will prove. Put unverified ideas in hypothesis instead. Return only JSON matching ToolUseDecision."
    return ToolUsePrompt(
        system_prompt=system_prompt,
        user_prompt=json.dumps(user_payload, ensure_ascii=True, indent=2),
        allowed=allowed,
        allowed_values=allowed_values,
    )
