"""Prompt builder for dispatch-fixed worker tool capability."""

from __future__ import annotations

import json
from typing import Any

from killchain_docker.state.run_state import RunState
from killchain_docker.state.todos import TodoItem
from killchain_docker.tools.capabilities import ToolCapability
from killchain_docker.workers.tooling.contracts.catalog import tool_metadata_contract
from killchain_docker.workers.prompts.model import ToolUsePrompt
from killchain_docker.workers.prompts.payload import fixed_tool_payload


def build_fixed_tool_prompt(
    *,
    worker_name: str,
    task: TodoItem,
    state: RunState,
    capability: ToolCapability | str,
    prior_steps: list[dict[str, Any]] | None,
) -> ToolUsePrompt:
    selected = ToolCapability(capability)
    user_payload = fixed_tool_payload(
        worker_name=worker_name,
        task=task,
        state=state,
        selected=selected,
        prior_steps=prior_steps,
        metadata_contract=tool_metadata_contract(selected),
    )
    fixed_rules = f"The router has already selected the capability. Do not choose or compare tools. Return ToolUseDecision with capability exactly '{selected.value}' and metadata matching metadata_contract. "
    if selected == ToolCapability.SCRIPT_EXEC:
        fixed_rules += "metadata.script_code must be complete bounded runnable source, prefer Python stdlib, use CTF_FILES_ROOT or relative paths for challenge files, use CTF_TEMP_DIR/tempfile for scratch, set network timeouts, print concise evidence, and do not install packages. Do not manually remove CTF_TEMP_DIR or tempfile.mkdtemp() directories after writing files there; the runner cleans scratch and publishes generated artifacts. "
    elif selected == ToolCapability.SHELL_EXEC:
        fixed_rules += "metadata.command must be a complete bash command using installed tools, with stderr visible and no package installation. "
    system_prompt = f"You are {worker_name}. {fixed_rules}Use recent_evidence_context and run_memory as grounded facts. cross_run_memory carries durable lessons from earlier runs (scope: global/category/challenge); treat them as priors that may shape your tool inputs, not as confirmed facts. If correction_context is present, fix that concrete runtime issue. Do not depend on files generated by previous tool calls unless the current todo references durable artifacts; regenerate transient scratch outputs in this same call. Stay inside authorized_scope and files_root. Return only JSON matching ToolUseDecision."
    return ToolUsePrompt(
        system_prompt=system_prompt,
        user_prompt=json.dumps(user_payload, ensure_ascii=True, indent=2),
        allowed={selected},
        allowed_values=[selected.value],
        fixed_capability=selected,
    )
